package com.github.lottery.common.dal;

import com.github.lottery.common.model.LotteryDrawing;
import com.github.lottery.common.model.LotteryDrawingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LotteryDrawingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_drawing
     *
     * @mbggenerated Mon Jul 23 23:35:54 CST 2018
     */
    int countByExample(LotteryDrawingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_drawing
     *
     * @mbggenerated Mon Jul 23 23:35:54 CST 2018
     */
    int deleteByExample(LotteryDrawingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_drawing
     *
     * @mbggenerated Mon Jul 23 23:35:54 CST 2018
     */
    int deleteByPrimaryKey(String issueno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_drawing
     *
     * @mbggenerated Mon Jul 23 23:35:54 CST 2018
     */
    int insert(LotteryDrawing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_drawing
     *
     * @mbggenerated Mon Jul 23 23:35:54 CST 2018
     */
    int insertSelective(LotteryDrawing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_drawing
     *
     * @mbggenerated Mon Jul 23 23:35:54 CST 2018
     */
    List<LotteryDrawing> selectByExample(LotteryDrawingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_drawing
     *
     * @mbggenerated Mon Jul 23 23:35:54 CST 2018
     */
    LotteryDrawing selectByPrimaryKey(String issueno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_drawing
     *
     * @mbggenerated Mon Jul 23 23:35:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") LotteryDrawing record, @Param("example") LotteryDrawingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_drawing
     *
     * @mbggenerated Mon Jul 23 23:35:54 CST 2018
     */
    int updateByExample(@Param("record") LotteryDrawing record, @Param("example") LotteryDrawingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_drawing
     *
     * @mbggenerated Mon Jul 23 23:35:54 CST 2018
     */
    int updateByPrimaryKeySelective(LotteryDrawing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lottery_drawing
     *
     * @mbggenerated Mon Jul 23 23:35:54 CST 2018
     */
    int updateByPrimaryKey(LotteryDrawing record);
}