package com.github.lottery.common.dal;

import com.github.lottery.common.model.UserScoreHistory;
import com.github.lottery.common.model.UserScoreHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserScoreHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score_history
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    int countByExample(UserScoreHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score_history
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    int deleteByExample(UserScoreHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score_history
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score_history
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    int insert(UserScoreHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score_history
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    int insertSelective(UserScoreHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score_history
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    List<UserScoreHistory> selectByExample(UserScoreHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score_history
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    UserScoreHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score_history
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserScoreHistory record, @Param("example") UserScoreHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score_history
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    int updateByExample(@Param("record") UserScoreHistory record, @Param("example") UserScoreHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score_history
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    int updateByPrimaryKeySelective(UserScoreHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score_history
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    int updateByPrimaryKey(UserScoreHistory record);
}