package com.github.lottery.common.model;

import java.util.Date;

public class LotteryHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_history.id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_history.issue_no
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private String issueNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_history.one
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer one;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_history.two
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer two;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_history.three
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer three;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_history.four
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer four;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_history.five
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer five;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_history.six
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer six;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_history.seven
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer seven;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_history.eight
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer eight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_history.nine
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer nine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_history.ten
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer ten;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_history.time
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lottery_history.create_time
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_history.id
     *
     * @return the value of lottery_history.id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_history.id
     *
     * @param id the value for lottery_history.id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_history.issue_no
     *
     * @return the value of lottery_history.issue_no
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public String getIssueNo() {
        return issueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_history.issue_no
     *
     * @param issueNo the value for lottery_history.issue_no
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setIssueNo(String issueNo) {
        this.issueNo = issueNo == null ? null : issueNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_history.one
     *
     * @return the value of lottery_history.one
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getOne() {
        return one;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_history.one
     *
     * @param one the value for lottery_history.one
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setOne(Integer one) {
        this.one = one;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_history.two
     *
     * @return the value of lottery_history.two
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getTwo() {
        return two;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_history.two
     *
     * @param two the value for lottery_history.two
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setTwo(Integer two) {
        this.two = two;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_history.three
     *
     * @return the value of lottery_history.three
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getThree() {
        return three;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_history.three
     *
     * @param three the value for lottery_history.three
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setThree(Integer three) {
        this.three = three;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_history.four
     *
     * @return the value of lottery_history.four
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getFour() {
        return four;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_history.four
     *
     * @param four the value for lottery_history.four
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setFour(Integer four) {
        this.four = four;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_history.five
     *
     * @return the value of lottery_history.five
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getFive() {
        return five;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_history.five
     *
     * @param five the value for lottery_history.five
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setFive(Integer five) {
        this.five = five;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_history.six
     *
     * @return the value of lottery_history.six
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getSix() {
        return six;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_history.six
     *
     * @param six the value for lottery_history.six
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setSix(Integer six) {
        this.six = six;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_history.seven
     *
     * @return the value of lottery_history.seven
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getSeven() {
        return seven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_history.seven
     *
     * @param seven the value for lottery_history.seven
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setSeven(Integer seven) {
        this.seven = seven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_history.eight
     *
     * @return the value of lottery_history.eight
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getEight() {
        return eight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_history.eight
     *
     * @param eight the value for lottery_history.eight
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setEight(Integer eight) {
        this.eight = eight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_history.nine
     *
     * @return the value of lottery_history.nine
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getNine() {
        return nine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_history.nine
     *
     * @param nine the value for lottery_history.nine
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setNine(Integer nine) {
        this.nine = nine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_history.ten
     *
     * @return the value of lottery_history.ten
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getTen() {
        return ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_history.ten
     *
     * @param ten the value for lottery_history.ten
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setTen(Integer ten) {
        this.ten = ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_history.time
     *
     * @return the value of lottery_history.time
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_history.time
     *
     * @param time the value for lottery_history.time
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lottery_history.create_time
     *
     * @return the value of lottery_history.create_time
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lottery_history.create_time
     *
     * @param createTime the value for lottery_history.create_time
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}