package com.github.lottery.common.model;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.issue_no
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private String issueNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.one
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private String one;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.two
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private String two;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.three
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private String three;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.four
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private String four;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.five
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private String five;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.six
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private String six;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.seven
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private String seven;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.eight
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private String eight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.nine
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private String nine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ten
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private String ten;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.income_score
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer incomeScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_time
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.total_score
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer totalScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.issue_no
     *
     * @return the value of orders.issue_no
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public String getIssueNo() {
        return issueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.issue_no
     *
     * @param issueNo the value for orders.issue_no
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setIssueNo(String issueNo) {
        this.issueNo = issueNo == null ? null : issueNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.one
     *
     * @return the value of orders.one
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public String getOne() {
        return one;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.one
     *
     * @param one the value for orders.one
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setOne(String one) {
        this.one = one == null ? null : one.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.two
     *
     * @return the value of orders.two
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public String getTwo() {
        return two;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.two
     *
     * @param two the value for orders.two
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setTwo(String two) {
        this.two = two == null ? null : two.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.three
     *
     * @return the value of orders.three
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public String getThree() {
        return three;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.three
     *
     * @param three the value for orders.three
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setThree(String three) {
        this.three = three == null ? null : three.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.four
     *
     * @return the value of orders.four
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public String getFour() {
        return four;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.four
     *
     * @param four the value for orders.four
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setFour(String four) {
        this.four = four == null ? null : four.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.five
     *
     * @return the value of orders.five
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public String getFive() {
        return five;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.five
     *
     * @param five the value for orders.five
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setFive(String five) {
        this.five = five == null ? null : five.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.six
     *
     * @return the value of orders.six
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public String getSix() {
        return six;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.six
     *
     * @param six the value for orders.six
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setSix(String six) {
        this.six = six == null ? null : six.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.seven
     *
     * @return the value of orders.seven
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public String getSeven() {
        return seven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.seven
     *
     * @param seven the value for orders.seven
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setSeven(String seven) {
        this.seven = seven == null ? null : seven.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.eight
     *
     * @return the value of orders.eight
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public String getEight() {
        return eight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.eight
     *
     * @param eight the value for orders.eight
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setEight(String eight) {
        this.eight = eight == null ? null : eight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.nine
     *
     * @return the value of orders.nine
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public String getNine() {
        return nine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.nine
     *
     * @param nine the value for orders.nine
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setNine(String nine) {
        this.nine = nine == null ? null : nine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ten
     *
     * @return the value of orders.ten
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public String getTen() {
        return ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ten
     *
     * @param ten the value for orders.ten
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setTen(String ten) {
        this.ten = ten == null ? null : ten.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.income_score
     *
     * @return the value of orders.income_score
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getIncomeScore() {
        return incomeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.income_score
     *
     * @param incomeScore the value for orders.income_score
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setIncomeScore(Integer incomeScore) {
        this.incomeScore = incomeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_time
     *
     * @return the value of orders.create_time
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_time
     *
     * @param createTime the value for orders.create_time
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.total_score
     *
     * @return the value of orders.total_score
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getTotalScore() {
        return totalScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.total_score
     *
     * @param totalScore the value for orders.total_score
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setTotalScore(Integer totalScore) {
        this.totalScore = totalScore;
    }
}