package com.github.lottery.common.model;

public class OrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail.id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail.no1
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer no1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail.no2
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer no2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail.no3
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer no3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail.no4
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer no4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail.no5
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer no5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail.no6
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer no6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail.no7
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer no7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail.no8
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer no8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail.no9
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer no9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_detail.no10
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer no10;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail.id
     *
     * @return the value of orders_detail.id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail.id
     *
     * @param id the value for orders_detail.id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail.no1
     *
     * @return the value of orders_detail.no1
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getNo1() {
        return no1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail.no1
     *
     * @param no1 the value for orders_detail.no1
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setNo1(Integer no1) {
        this.no1 = no1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail.no2
     *
     * @return the value of orders_detail.no2
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getNo2() {
        return no2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail.no2
     *
     * @param no2 the value for orders_detail.no2
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setNo2(Integer no2) {
        this.no2 = no2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail.no3
     *
     * @return the value of orders_detail.no3
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getNo3() {
        return no3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail.no3
     *
     * @param no3 the value for orders_detail.no3
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setNo3(Integer no3) {
        this.no3 = no3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail.no4
     *
     * @return the value of orders_detail.no4
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getNo4() {
        return no4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail.no4
     *
     * @param no4 the value for orders_detail.no4
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setNo4(Integer no4) {
        this.no4 = no4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail.no5
     *
     * @return the value of orders_detail.no5
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getNo5() {
        return no5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail.no5
     *
     * @param no5 the value for orders_detail.no5
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setNo5(Integer no5) {
        this.no5 = no5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail.no6
     *
     * @return the value of orders_detail.no6
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getNo6() {
        return no6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail.no6
     *
     * @param no6 the value for orders_detail.no6
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setNo6(Integer no6) {
        this.no6 = no6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail.no7
     *
     * @return the value of orders_detail.no7
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getNo7() {
        return no7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail.no7
     *
     * @param no7 the value for orders_detail.no7
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setNo7(Integer no7) {
        this.no7 = no7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail.no8
     *
     * @return the value of orders_detail.no8
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getNo8() {
        return no8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail.no8
     *
     * @param no8 the value for orders_detail.no8
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setNo8(Integer no8) {
        this.no8 = no8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail.no9
     *
     * @return the value of orders_detail.no9
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getNo9() {
        return no9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail.no9
     *
     * @param no9 the value for orders_detail.no9
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setNo9(Integer no9) {
        this.no9 = no9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_detail.no10
     *
     * @return the value of orders_detail.no10
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getNo10() {
        return no10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_detail.no10
     *
     * @param no10 the value for orders_detail.no10
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setNo10(Integer no10) {
        this.no10 = no10;
    }
}