package com.github.lottery.common.model;

import java.util.Date;

public class UserScoreHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_score_history.id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_score_history.user_id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_score_history.score_type
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer scoreType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_score_history.score_value
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer scoreValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_score_history.crt_balance
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Integer crtBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_score_history.remark
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_score_history.create_time
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_score_history.id
     *
     * @return the value of user_score_history.id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_score_history.id
     *
     * @param id the value for user_score_history.id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_score_history.user_id
     *
     * @return the value of user_score_history.user_id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_score_history.user_id
     *
     * @param userId the value for user_score_history.user_id
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_score_history.score_type
     *
     * @return the value of user_score_history.score_type
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getScoreType() {
        return scoreType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_score_history.score_type
     *
     * @param scoreType the value for user_score_history.score_type
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setScoreType(Integer scoreType) {
        this.scoreType = scoreType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_score_history.score_value
     *
     * @return the value of user_score_history.score_value
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getScoreValue() {
        return scoreValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_score_history.score_value
     *
     * @param scoreValue the value for user_score_history.score_value
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setScoreValue(Integer scoreValue) {
        this.scoreValue = scoreValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_score_history.crt_balance
     *
     * @return the value of user_score_history.crt_balance
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Integer getCrtBalance() {
        return crtBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_score_history.crt_balance
     *
     * @param crtBalance the value for user_score_history.crt_balance
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setCrtBalance(Integer crtBalance) {
        this.crtBalance = crtBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_score_history.remark
     *
     * @return the value of user_score_history.remark
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_score_history.remark
     *
     * @param remark the value for user_score_history.remark
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_score_history.create_time
     *
     * @return the value of user_score_history.create_time
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_score_history.create_time
     *
     * @param createTime the value for user_score_history.create_time
     *
     * @mbggenerated Sun Jun 24 16:05:35 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}